name = "uptimeflare_worker"
main = "src/index.ts"
compatibility_date = "2025-04-02"
kv_namespaces = [
  { binding = "UPTIMEFLARE_STATE", id = "37f121d3eb614879a9f5eaa40c9eaddd" }
]
triggers = { crons = ["*/1 * * * *"] }
